Update docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -30,7 +30,14 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Extract Git tag
+        if: startsWith(github.ref, 'refs/tags/')
         run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+      - name: Validate Git tag
+        run: |
+          if [ -z "${{ env.GIT_TAG }}" ]; then
+            echo "ERROR: No valid Git tag found!"
+            exit 1
+          fi
       - name: Build and push versioned Docker image
         id: build-and-push
         uses: docker/build-push-action@v5
